repos:
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    sha: ''  # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args: ['--single-quote'] #list of args like '--single-quote', '--jsx-bracket-same-line', '--print-width 120', '--no-bracket-spacing'
        additional_dependencies: ['prettier@1.1.0']
