export const CONNECT_SOUNDCLOUD = "CONNECT_SOUNDCLOUD"
export const PAUSE_SNIPPET = "PAUSE_SNIPPET"
export const PLAY_SNIPPET = "PLAY_SNIPPET"
export const SET_SNIPPET = "SET_SNIPPET"
export const UPDATE_TRACK_TIME = "UPDATE_TRACK_TIME"

export const NEXT_SNIPPET = "NEXT_SNIPPET"
export const PREV_SNIPPET = "PREV_SNIPPET"



export const UPDATE_PLAYLIST = "UPDATE_PLAYLIST"
export const APPEND_PLAYLIST = "APPEND_PLAYLIST"
export const CLEAR_PLAYLIST = "CLEAR_PLAYLIST"


export const GET_TRACK = "GET_TRACK"


export const SET_SHORT_ID = "SET_SHORT_ID"



// Track Index
export const UPDATE_CURRENT_INDEX = "UPDATE_CURRENT_INDEX"
