export const CONNECT_SOUNDCLOUD = 'CONNECT_SOUNDCLOUD';
export const PAUSE_SNIPPET = 'PAUSE_SNIPPET';
export const PLAY_SNIPPET = 'PLAY_SNIPPET';
export const SET_SNIPPET = 'SET_SNIPPET';

export const UPDATE_TRACK_TIME = 'UPDATE_TRACK_TIME';

export const NEXT_SNIPPET = 'NEXT_SNIPPET';
export const PREV_SNIPPET = 'PREV_SNIPPET';

export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const APPEND_PLAYLIST = 'APPEND_PLAYLIST';
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';

export const GET_TRACK = 'GET_TRACK';

export const SET_SHORT_ID = 'SET_SHORT_ID';

// Track Index
export const UPDATE_CURRENT_INDEX = 'UPDATE_CURRENT_INDEX';

// New
export const NEW_UPDATE_PLUG = 'NEW_UPDATE_PLUG';
export const NEW_APPEND_PLUG = 'NEW_APPEND_PLUG';
export const NEW_CLEAR_PLUG = 'NEW_CLEAR_PLUG';
export const NEW_SHIFT_CURRENT_PLUG = 'NEW_SHIFT_CURRENT_PLUG';
export const NEW_SHIFT_CURRENT_TRACK = 'NEW_SHIFT_CURRENT_TRACK';

export const NEW_UPDATE_TRACK_INDEX = 'NEW_UPDATE_TRACK_INDEX';
export const NEW_UPDATE_PLUG_INDEX = 'NEW_UPDATE_PLUG_INDEX';
export const NEW_INCREMENT_TOTAL_TRACK_INDEX =
	'NEW_INCREMENT_TOTAL_TRACK_INDEX';

export const CLEAR_ALL = 'CLEAR_ALL';


export const TRACK_LOADING = 'TRACK_LOADING';
