export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER"

export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"


export const GET_USER_ROLE = "GET_USER_ROLE"
export const GET_SUBSCRIPTION_DETAILS = "GET_SUBSCRIPTION_DETAILS"

