export const GET_SOUNDCLOUD_ERRORS = "GET_SOUNDCLOUD_ERRORS"
export const CLEAR_SOUNDCLOUD_ERRORS = "CLEAR_SOUNDCLOUD_ERRORS"


export const GET_SEARCH_ERRORS = "GET_SEARCH_ERRORS"
export const CLEAR_SEARCH_ERRORS = "CLEAR_SEARCH_ERRORS"


// Register
export const GET_REGISTER_ERRORS = "GET_REGISTER_ERRORS"
export const CLEAR_REGISTER_ERRORS = "CLEAR_REGISTER_ERRORS"

// Login
export const GET_LOGIN_ERRORS = "GET_LOGIN_ERRORS"
export const CLEAR_LOGIN_ERRORS = "CLEAR_LOGIN_ERRORS"

// API
export const GET_PLUG_ERRORS = "GET_PLUG_ERRORS"
export const CLEAR_PLUG_ERRORS = "GET_PLUG_ERRORS"